### ISSUE TITLE
testament failure in Nim CI

### ISSUE THREAD

**Issue by c-blake** [zero-functional/zero-functional#60]
So, there is a weird test failure for zero-functional at the very bottom of https://dev.azure.com/nim-lang/Nim/_build/results?buildId=4178&view=logs&jobId=c69e982b-684a-5fe0-85d3-75c46c27e054&j=c69e982b-684a-5fe0-85d3-75c46c27e054&t=21e7e6f9-f581-5817-b641-fee9213e925d

As mentioned in https://github.com/nim-lang/Nim/pull/13823#issuecomment-611523525 it looks more related to the way testament is running your tests than to the change of `hash(int)` function/ordering in `Table`/`HashSet` itself.  Has this sort of test failure happened before?  Thanks in advance for any help you can provide.

**Comment by c-blake** [comment]
Apologies.  I misinterpreted the output of the CI.  Your tests do not fail.

**Comment by alehander92** [comment]
sorry, i just saw this! happy that its fixed

**Comment by michael72** [comment]
always bad to be the last in the alphabet ;-)
