### ISSUE TITLE
Extending with DSL results in undeclared identifier error.

### ISSUE THREAD

**Issue by ZoomRmc** [zero-functional/zero-functional#65]
Nim 1.4.2
Using the example from Readme:
```
zfInline filter(cond: bool):
  loop:
    if cond:
      yield it # add the current iterator to the resulting collection
```
Results in:
`zero_functional.nim(959, 24) Error: undeclared identifier: 'newIdentNode'`

**Comment by michael72** [comment]
you could add
` import macros`

**Comment by ZoomRmc** [comment]
Thanks, this was not clear from the docs.
Also, the note about registering the extension with `zfCreateExtension` should probably be moved to the top of the section and not omitted from at least the first example.

**Comment by michael72** [comment]
would have been an opportunity to do a PR - but well...
@ZoomRmc updated documentation - closing this one

**Comment by ZoomRmc** [comment]
Sorry, I'm to new to the library to be aware of any consequences of messing with the docs/the code yet.
