### ISSUE TITLE
Feature: Add `to(hashSet)`, `to(packedSet)`, `to(set)`

### ISSUE THREAD

**Issue by awr1** [zero-functional/zero-functional#69]
Right now to transform the result of a zero-functional routine into a hash-set type, one must first either obtain the result as a sequence and then convert it using `toHashSet`/`toPackedSet`/etc. (inefficient due to the created sequence, somewhat unwieldly) or use `createIter` and then build up the set from that, possibly using `collect` (which is also unwieldly). 

IMO having the ability to use hash-sets for the result types would be a welcome addition. As an addition, since enums are also iterable in ZF, allowing for results of type `set[T]` would go hand in hand with any added support for hash-set types and would also leave ZF with complete support for outputting to Nim's standard set types.

**Comment by hamidb80** [comment]
take a look at [itter](https://github.com/hamidb80/iterrr). 
you can define your custom reducer simply. [due to the implementation]

**Comment by michael72** [comment]
The output type has to be set explicitly using `to(HashSet[int])` for instance - so the type has to be known for that.

Due to a an internal bug the transformation wasn't working in some cases. That has been fixed. For instance

```nim
import zero_functional, sets

let x = 1..10 --> filter(it mod 2 == 1) --> map(it * 2) --> map(it + 2) -->> to(set[int])
echo(x)
```

will generate compiler output

```nim
# test2.nim:3
# 1 .. 10.zfun:
#   filter(it mod 2 == 1)
#   map:
#     it * 2
#     it + 2
#   to(set[int])
(proc (): auto =
  var res: HashSet[int]
  result = zfInit(res)
  var idx = 0
  for it0 in 1 .. 10:
    if it0 mod 2 == 1:
      let it1 = it0 * 2
      let it2 = it1 + 2
      zfAddItemChk(result, idx, it2, "int", "HashSet[int]", false)
    idx += 1)()
```

Where `zfAddItemChk` does a few compile checks and delegates to a simple adder.
When run it prints the output:

```log
{4, 16, 12, 20, 8}
```
