### ISSUE TITLE
slower than sequtils/sugar ?

### ISSUE THREAD

**Issue by greenersharp** [zero-functional/zero-functional#86]
Hi,

I'm learning Nim and just learnt about this interesting library.
I've been using sequtils/sugar to chain code and was interested in learning that the zero-functional library can make this more effieient.

I tried a simple example that goes over the bible, splits into sentences, finds sentences that have the word " and ", and then returns to me the last word in these matching sentences.

I then compared it to sequtils and used bency to bechmark it.   

Results here:

```
import zero_functional, strutils, benchy, sequtils, sugar

timeit "zero":
    let words = readfile("bible.txt").split("\n") --> filter(" and " in it).map(it.split(" ")[^1])
    # echo words[0..10]  ==  @["earth", "waters", "light", "darkness", "day", "waters", "so", "day", "so", "good", "so"]

timeit "seq":
    let words = readfile("bible.txt").split("\n").filterit(" and " in it).mapit(it.split(" ")[^1])
    # echo words[0..10]  ==  @["earth", "waters", "light", "darkness", "day", "waters", "so", "day", "so", "good", "so"]



   # min time    avg time  std dv   runs name
  # 62.009 ms   63.193 ms  ±0.853    x79 zero
  # 50.847 ms   52.025 ms  ±0.786    x97 seq
```

I'm just wondering why zero-funcitonal is about 18% slower in this case.

Thank you

**Comment by michael72** [comment]
Hm - so I get quite similar results when compiling your example with `-d:release` (and downloading some bible.txt)
So - this library is a bit older meanwhile and it looks like Nim got faster, but still comparing the benchmarks that are inside this project (unfortunately the internal Bench does not work any more but using benchy) I get:

zf version:

```log
   min time    avg time  std dv   runs name
   6.949 ms    7.162 ms  ±0.125   x696 example0
   0.640 ms    0.690 ms  ±0.033  x1000 example1
```

vs "sequtils" version:

```log
   min time    avg time  std dv   runs name
  15.242 ms   16.712 ms  ±0.459   x299 example0
   5.598 ms    5.901 ms  ±0.141   x846 example1
```

Hm. So I guess it depends on what and how many operations you perform on the data.

**Comment by greenersharp** [comment]
Interesting, so zero-functional is definitely much faster is some cases, I will experiment more, thank you !
